2023-12-05 07:41:40,053 INFO    StreamThr :32909 [internal.py:wandb_internal():86] W&B internal server running at pid: 32909, started at: 2023-12-05 07:41:40.051106
2023-12-05 07:41:40,056 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status
2023-12-05 07:41:40,064 INFO    WriterThread:32909 [datastore.py:open_for_write():85] open: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/run-kidytdy0.wandb
2023-12-05 07:41:40,066 DEBUG   SenderThread:32909 [sender.py:send():380] send: header
2023-12-05 07:41:40,089 DEBUG   SenderThread:32909 [sender.py:send():380] send: run
2023-12-05 07:41:40,745 INFO    SenderThread:32909 [dir_watcher.py:__init__():211] watching files in: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files
2023-12-05 07:41:40,745 INFO    SenderThread:32909 [sender.py:_start_run_threads():1122] run started: kidytdy0 with start time 1701762100.055566
2023-12-05 07:41:40,790 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: check_version
2023-12-05 07:41:40,791 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: check_version
2023-12-05 07:41:41,075 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: run_start
2023-12-05 07:41:41,099 DEBUG   HandlerThread:32909 [system_info.py:__init__():32] System info init
2023-12-05 07:41:41,100 DEBUG   HandlerThread:32909 [system_info.py:__init__():47] System info init done
2023-12-05 07:41:41,100 INFO    HandlerThread:32909 [system_monitor.py:start():181] Starting system monitor
2023-12-05 07:41:41,100 INFO    SystemMonitor:32909 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-12-05 07:41:41,101 INFO    HandlerThread:32909 [system_monitor.py:probe():201] Collecting system info
2023-12-05 07:41:41,102 INFO    SystemMonitor:32909 [interfaces.py:start():190] Started cpu monitoring
2023-12-05 07:41:41,104 INFO    SystemMonitor:32909 [interfaces.py:start():190] Started disk monitoring
2023-12-05 07:41:41,106 INFO    SystemMonitor:32909 [interfaces.py:start():190] Started gpu monitoring
2023-12-05 07:41:41,109 INFO    SystemMonitor:32909 [interfaces.py:start():190] Started memory monitoring
2023-12-05 07:41:41,112 INFO    SystemMonitor:32909 [interfaces.py:start():190] Started network monitoring
2023-12-05 07:41:41,208 DEBUG   HandlerThread:32909 [system_info.py:probe():196] Probing system
2023-12-05 07:41:41,214 DEBUG   HandlerThread:32909 [system_info.py:_probe_git():181] Probing git
2023-12-05 07:41:41,233 DEBUG   HandlerThread:32909 [system_info.py:_probe_git():189] Probing git done
2023-12-05 07:41:41,233 DEBUG   HandlerThread:32909 [system_info.py:probe():244] Probing system done
2023-12-05 07:41:41,233 DEBUG   HandlerThread:32909 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-78-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2023-12-05T07:41:41.208603', 'startedAt': '2023-12-05T07:41:40.023557', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/yishido/self_supervied/notpredictor_resnet.py', 'codePathLocal': 'notpredictor_resnet.py', 'codePath': 'notpredictor_resnet.py', 'git': {'remote': 'git@github.com:yuzuki-lab/self-supervised.git', 'commit': 'c441728209ccdd4671d6a297411fd3e05f4d9551'}, 'email': '117724724+yuzuki-lab@users.noreply.github.com', 'root': '/home/yishido/self_supervied', 'host': 'mach01', 'username': 'yishido', 'executable': '/home/yishido/.pyenv/versions/3.10.12/bin/python', 'cpu_count': 32, 'cpu_count_logical': 32, 'cpu_freq': {'current': 1785.2275000000002, 'min': 1500.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3300.004, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1499.052, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2398.619, 'min': 1500.0, 'max': 3000.0}], 'disk': {'/': {'total': 1876.7089385986328, 'used': 73.20021057128906}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 251.74816131591797}}
2023-12-05 07:41:41,234 INFO    HandlerThread:32909 [system_monitor.py:probe():211] Finished collecting system info
2023-12-05 07:41:41,234 INFO    HandlerThread:32909 [system_monitor.py:probe():214] Publishing system info
2023-12-05 07:41:41,234 DEBUG   HandlerThread:32909 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-05 07:41:41,237 DEBUG   HandlerThread:32909 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-05 07:41:41,241 INFO    HandlerThread:32909 [system_monitor.py:probe():216] Finished publishing system info
2023-12-05 07:41:41,303 DEBUG   SenderThread:32909 [sender.py:send():380] send: files
2023-12-05 07:41:41,303 INFO    SenderThread:32909 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-12-05 07:41:41,317 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:41:41,317 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:41:41,324 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:41:41,753 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/requirements.txt
2023-12-05 07:41:41,754 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/wandb-metadata.json
2023-12-05 07:41:41,757 DEBUG   SenderThread:32909 [sender.py:send():380] send: telemetry
2023-12-05 07:41:42,196 INFO    wandb-upload_0:32909 [upload_job.py:push():131] Uploaded file /tmp/tmpcvkivcikwandb/nwbnsu2g-wandb-metadata.json
2023-12-05 07:41:45,758 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:41:50,759 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:41:55,760 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:41:56,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:41:56,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:41:56,322 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:01,612 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:06,612 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:11,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:11,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:11,322 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:12,585 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:13,806 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/config.yaml
2023-12-05 07:42:18,135 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:23,136 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:25,828 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
2023-12-05 07:42:26,318 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:26,320 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:26,321 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:27,829 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
2023-12-05 07:42:28,651 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:34,214 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:35,839 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
2023-12-05 07:42:39,215 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:41,112 DEBUG   SystemMonitor:32909 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-12-05 07:42:41,117 DEBUG   SenderThread:32909 [sender.py:send():380] send: stats
2023-12-05 07:42:41,319 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:41,320 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:41,324 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:41,843 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
2023-12-05 07:42:44,615 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:49,616 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:54,617 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:56,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:56,322 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:56,361 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:59,864 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:04,865 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:09,866 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:11,126 DEBUG   SenderThread:32909 [sender.py:send():380] send: stats
2023-12-05 07:43:11,294 ERROR   FileStreamThread:32909 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/a_citrus/SimSiam/kidytdy0/file_stream
NoneType: None
2023-12-05 07:43:11,321 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:43:11,323 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:43:11,365 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:43:15,510 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:15,894 DEBUG   SenderThread:32909 [sender.py:send():380] send: exit
2023-12-05 07:43:15,895 INFO    SenderThread:32909 [sender.py:send_exit():585] handling exit code: 255
2023-12-05 07:43:15,895 INFO    SenderThread:32909 [sender.py:send_exit():587] handling runtime: 94
2023-12-05 07:43:15,897 INFO    SenderThread:32909 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-12-05 07:43:15,897 INFO    SenderThread:32909 [sender.py:send_exit():593] send defer
2023-12-05 07:43:15,898 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:15,898 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 0
2023-12-05 07:43:15,899 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:15,899 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 0
2023-12-05 07:43:15,899 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 1
2023-12-05 07:43:15,899 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:15,900 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 1
2023-12-05 07:43:15,901 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:15,901 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 1
2023-12-05 07:43:15,901 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 2
2023-12-05 07:43:15,901 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:15,902 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 2
2023-12-05 07:43:15,902 INFO    HandlerThread:32909 [system_monitor.py:finish():190] Stopping system monitor
2023-12-05 07:43:15,903 DEBUG   SystemMonitor:32909 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-12-05 07:43:15,904 INFO    HandlerThread:32909 [interfaces.py:finish():202] Joined cpu monitor
2023-12-05 07:43:15,904 DEBUG   SystemMonitor:32909 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-12-05 07:43:15,905 INFO    HandlerThread:32909 [interfaces.py:finish():202] Joined disk monitor
2023-12-05 07:43:16,644 INFO    HandlerThread:32909 [interfaces.py:finish():202] Joined gpu monitor
2023-12-05 07:43:16,645 INFO    HandlerThread:32909 [interfaces.py:finish():202] Joined memory monitor
2023-12-05 07:43:16,646 INFO    HandlerThread:32909 [interfaces.py:finish():202] Joined network monitor
2023-12-05 07:43:16,648 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,648 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 2
2023-12-05 07:43:16,648 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 3
2023-12-05 07:43:16,649 DEBUG   SenderThread:32909 [sender.py:send():380] send: stats
2023-12-05 07:43:16,649 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:16,651 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 3
2023-12-05 07:43:16,652 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,652 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 3
2023-12-05 07:43:16,652 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 4
2023-12-05 07:43:16,652 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:16,653 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 4
2023-12-05 07:43:16,653 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,654 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 4
2023-12-05 07:43:16,654 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 5
2023-12-05 07:43:16,654 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:16,654 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 5
2023-12-05 07:43:16,655 DEBUG   SenderThread:32909 [sender.py:send():380] send: summary
2023-12-05 07:43:16,658 INFO    SenderThread:32909 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-12-05 07:43:16,659 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,659 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 5
2023-12-05 07:43:16,659 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 6
2023-12-05 07:43:16,659 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:16,659 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 6
2023-12-05 07:43:16,660 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,660 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 6
2023-12-05 07:43:16,660 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 7
2023-12-05 07:43:16,660 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:16,661 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:16,661 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 7
2023-12-05 07:43:16,662 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:16,662 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 7
2023-12-05 07:43:16,895 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:16,899 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/wandb-summary.json
2023-12-05 07:43:17,876 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 8
2023-12-05 07:43:17,876 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:17,877 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:17,877 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 8
2023-12-05 07:43:17,878 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:17,878 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 8
2023-12-05 07:43:17,879 INFO    SenderThread:32909 [job_builder.py:build():281] Attempting to build job artifact
2023-12-05 07:43:17,880 INFO    SenderThread:32909 [job_builder.py:_get_source_type():393] is repo sourced job
2023-12-05 07:43:17,890 INFO    SenderThread:32909 [job_builder.py:build():369] adding wandb-job metadata file
2023-12-05 07:43:17,897 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:17,901 INFO    Thread-12 :32909 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
2023-12-05 07:43:17,906 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 9
2023-12-05 07:43:17,906 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:17,906 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:17,907 DEBUG   SenderThread:32909 [sender.py:send():380] send: artifact
2023-12-05 07:43:17,908 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 9
2023-12-05 07:43:18,762 ERROR   SenderThread:32909 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-12-05 07:43:18,762 ERROR   SenderThread:32909 [internal_api.py:execute():370] {"errors":[{"message":"failed to find run SimSiam/kidytdy0","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2023-12-05 07:43:18,765 ERROR   SenderThread:32909 [sender.py:send_artifact():1458] send_artifact: failed for artifact "job/job-git_github.com_yuzuki-lab_self-supervised.git_notpredictor_resnet.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-05 07:43:18,766 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:18,766 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 9
2023-12-05 07:43:18,766 INFO    SenderThread:32909 [dir_watcher.py:finish():358] shutting down directory watcher
2023-12-05 07:43:18,898 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:18,903 INFO    SenderThread:32909 [dir_watcher.py:finish():388] scan: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files
2023-12-05 07:43:18,904 INFO    SenderThread:32909 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/config.yaml config.yaml
2023-12-05 07:43:18,904 INFO    SenderThread:32909 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/requirements.txt requirements.txt
2023-12-05 07:43:18,911 INFO    SenderThread:32909 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/wandb-metadata.json wandb-metadata.json
2023-12-05 07:43:18,911 INFO    SenderThread:32909 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log output.log
2023-12-05 07:43:18,913 INFO    SenderThread:32909 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/wandb-summary.json wandb-summary.json
2023-12-05 07:43:18,921 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 10
2023-12-05 07:43:18,921 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:18,922 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:18,922 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 10
2023-12-05 07:43:18,934 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:18,938 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 10
2023-12-05 07:43:18,938 INFO    SenderThread:32909 [file_pusher.py:finish():175] shutting down file pusher
2023-12-05 07:43:19,078 ERROR   wandb-upload_0:32909 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-12-05 07:43:19,078 ERROR   wandb-upload_0:32909 [internal_api.py:execute():370] {"errors":[{"message":"run SimSiam/kidytdy0 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-12-05 07:43:19,079 ERROR   Thread-11 (_thread_body):32909 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/config.yaml
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-05 07:43:19,101 ERROR   wandb-upload_1:32909 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-12-05 07:43:19,102 ERROR   wandb-upload_1:32909 [internal_api.py:execute():370] {"errors":[{"message":"run SimSiam/kidytdy0 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-12-05 07:43:19,102 ERROR   Thread-11 (_thread_body):32909 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/requirements.txt
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-05 07:43:19,391 ERROR   wandb-upload_3:32909 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-12-05 07:43:19,391 ERROR   wandb-upload_3:32909 [internal_api.py:execute():370] {"errors":[{"message":"run SimSiam/kidytdy0 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-12-05 07:43:19,392 ERROR   Thread-11 (_thread_body):32909 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-05 07:43:19,402 ERROR   wandb-upload_2:32909 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-12-05 07:43:19,402 ERROR   wandb-upload_2:32909 [internal_api.py:execute():370] {"errors":[{"message":"run SimSiam/kidytdy0 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-12-05 07:43:19,403 ERROR   Thread-11 (_thread_body):32909 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/files/output.log
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-05 07:43:19,605 INFO    Thread-11 (_thread_body):32909 [sender.py:transition_state():613] send defer: 11
2023-12-05 07:43:19,605 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:19,606 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 11
2023-12-05 07:43:19,607 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:19,607 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 11
2023-12-05 07:43:19,607 INFO    SenderThread:32909 [file_pusher.py:join():181] waiting for file pusher
2023-12-05 07:43:19,608 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 12
2023-12-05 07:43:19,608 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:19,608 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 12
2023-12-05 07:43:19,609 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:19,610 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 12
2023-12-05 07:43:19,610 INFO    SenderThread:32909 [file_stream.py:finish():595] file stream finish called
2023-12-05 07:43:19,771 ERROR   FileStreamThread:32909 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/a_citrus/SimSiam/kidytdy0/file_stream
NoneType: None
2023-12-05 07:43:19,900 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:19,930 INFO    SenderThread:32909 [file_stream.py:finish():599] file stream finish is done
2023-12-05 07:43:19,930 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 13
2023-12-05 07:43:19,931 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:19,931 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:19,932 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 13
2023-12-05 07:43:19,933 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:19,934 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 13
2023-12-05 07:43:19,934 INFO    SenderThread:32909 [sender.py:transition_state():613] send defer: 14
2023-12-05 07:43:19,935 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: defer
2023-12-05 07:43:19,936 INFO    HandlerThread:32909 [handler.py:handle_request_defer():170] handle defer: 14
2023-12-05 07:43:19,936 DEBUG   SenderThread:32909 [sender.py:send():380] send: final
2023-12-05 07:43:19,937 DEBUG   SenderThread:32909 [sender.py:send():380] send: footer
2023-12-05 07:43:19,937 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: defer
2023-12-05 07:43:19,938 INFO    SenderThread:32909 [sender.py:send_request_defer():609] handle sender defer: 14
2023-12-05 07:43:19,939 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:19,940 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:19,941 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:19,942 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: poll_exit
2023-12-05 07:43:19,943 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: server_info
2023-12-05 07:43:19,944 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: server_info
2023-12-05 07:43:19,950 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: get_summary
2023-12-05 07:43:19,954 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: sampled_history
2023-12-05 07:43:19,955 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:43:19,956 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: job_info
2023-12-05 07:43:20,114 DEBUG   SenderThread:32909 [sender.py:send_request():407] send_request: job_info
2023-12-05 07:43:20,115 INFO    MainThread:32909 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-12-05 07:43:20,115 INFO    MainThread:32909 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-12-05 07:43:20,116 INFO    MainThread:32909 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-12-05 07:43:20,116 DEBUG   HandlerThread:32909 [handler.py:handle_request():144] handle_request: shutdown
2023-12-05 07:43:20,117 INFO    HandlerThread:32909 [handler.py:finish():844] shutting down handler
2023-12-05 07:43:20,957 INFO    WriterThread:32909 [datastore.py:close():294] close: /home/yishido/self_supervied/wandb/run-20231205_074140-kidytdy0/run-kidytdy0.wandb
2023-12-05 07:43:21,115 INFO    SenderThread:32909 [sender.py:finish():1534] shutting down sender
2023-12-05 07:43:21,115 INFO    SenderThread:32909 [file_pusher.py:finish():175] shutting down file pusher
2023-12-05 07:43:21,115 INFO    SenderThread:32909 [file_pusher.py:join():181] waiting for file pusher
