
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Data loaded: there are 5000 train images.
Starting training !
Traceback (most recent call last):
  File "/home/yishido/self_supervied/base.py", line 348, in <module>
    main()
  File "/home/yishido/self_supervied/base.py", line 213, in main
    knn_acc, linear_acc = val(acc_train_loader,acc_val_loader,model,device)
  File "/home/yishido/self_supervied/base.py", line 265, in val
    (train_X, train_y, test_X, test_y) = get_features(model, acc_train_loader, acc_val_loader, 'cuda')
  File "/home/yishido/self_supervied/base.py", line 326, in get_features
    train_X, train_y = inference(train_loader, model, device)
  File "/home/yishido/self_supervied/base.py", line 310, in inference
    h = model(x)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)