2023-11-29 13:23:26,703 INFO    StreamThr :1507375 [internal.py:wandb_internal():86] W&B internal server running at pid: 1507375, started at: 2023-11-29 13:23:26.702108
2023-11-29 13:23:26,707 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status
2023-11-29 13:23:26,711 INFO    WriterThread:1507375 [datastore.py:open_for_write():85] open: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/run-9w8csl2q.wandb
2023-11-29 13:23:26,715 DEBUG   SenderThread:1507375 [sender.py:send():380] send: header
2023-11-29 13:23:26,724 DEBUG   SenderThread:1507375 [sender.py:send():380] send: run
2023-11-29 13:23:27,809 INFO    SenderThread:1507375 [dir_watcher.py:__init__():211] watching files in: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files
2023-11-29 13:23:27,809 INFO    SenderThread:1507375 [sender.py:_start_run_threads():1122] run started: 9w8csl2q with start time 1701264206.704133
2023-11-29 13:23:27,864 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: check_version
2023-11-29 13:23:27,866 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: check_version
2023-11-29 13:23:28,142 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: run_start
2023-11-29 13:23:28,161 DEBUG   HandlerThread:1507375 [system_info.py:__init__():32] System info init
2023-11-29 13:23:28,161 DEBUG   HandlerThread:1507375 [system_info.py:__init__():47] System info init done
2023-11-29 13:23:28,161 INFO    HandlerThread:1507375 [system_monitor.py:start():181] Starting system monitor
2023-11-29 13:23:28,162 INFO    SystemMonitor:1507375 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-11-29 13:23:28,162 INFO    HandlerThread:1507375 [system_monitor.py:probe():201] Collecting system info
2023-11-29 13:23:28,164 INFO    SystemMonitor:1507375 [interfaces.py:start():190] Started cpu monitoring
2023-11-29 13:23:28,166 INFO    SystemMonitor:1507375 [interfaces.py:start():190] Started disk monitoring
2023-11-29 13:23:28,169 INFO    SystemMonitor:1507375 [interfaces.py:start():190] Started gpu monitoring
2023-11-29 13:23:28,170 INFO    SystemMonitor:1507375 [interfaces.py:start():190] Started memory monitoring
2023-11-29 13:23:28,171 INFO    SystemMonitor:1507375 [interfaces.py:start():190] Started network monitoring
2023-11-29 13:23:28,268 DEBUG   HandlerThread:1507375 [system_info.py:probe():196] Probing system
2023-11-29 13:23:28,273 DEBUG   HandlerThread:1507375 [system_info.py:_probe_git():181] Probing git
2023-11-29 13:23:28,290 DEBUG   HandlerThread:1507375 [system_info.py:_probe_git():189] Probing git done
2023-11-29 13:23:28,290 DEBUG   HandlerThread:1507375 [system_info.py:probe():244] Probing system done
2023-11-29 13:23:28,290 DEBUG   HandlerThread:1507375 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-78-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2023-11-29T13:23:28.268609', 'startedAt': '2023-11-29T13:23:26.671830', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/yishido/self_supervied/stl_resnet.py', 'codePathLocal': 'stl_resnet.py', 'codePath': 'stl_resnet.py', 'git': {'remote': 'git@github.com:yuzuki-lab/self-supervised.git', 'commit': '8de7840d7cad20fb9fbfdf11b3f380a59ca6b2a4'}, 'email': '117724724+yuzuki-lab@users.noreply.github.com', 'root': '/home/yishido/self_supervied', 'host': 'mach01', 'username': 'yishido', 'executable': '/home/yishido/.pyenv/versions/3.10.12/bin/python', 'cpu_count': 32, 'cpu_count_logical': 32, 'cpu_freq': {'current': 2879.9141874999996, 'min': 1500.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.236, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.308, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3295.109, 'min': 1500.0, 'max': 3000.0}, {'current': 3297.789, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3297.805, 'min': 1500.0, 'max': 3000.0}, {'current': 3029.819, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3294.367, 'min': 1500.0, 'max': 3000.0}, {'current': 3299.935, 'min': 1500.0, 'max': 3000.0}, {'current': 3299.893, 'min': 1500.0, 'max': 3000.0}, {'current': 3297.924, 'min': 1500.0, 'max': 3000.0}, {'current': 3297.697, 'min': 1500.0, 'max': 3000.0}, {'current': 2192.891, 'min': 1500.0, 'max': 3000.0}, {'current': 3297.298, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.613, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.629, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3295.461, 'min': 1500.0, 'max': 3000.0}, {'current': 3295.863, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.069, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3298.195, 'min': 1500.0, 'max': 3000.0}, {'current': 3298.743, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2198.15, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.726, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3298.261, 'min': 1500.0, 'max': 3000.0}], 'disk': {'/': {'total': 1876.7089385986328, 'used': 72.88568878173828}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 251.74816131591797}}
2023-11-29 13:23:28,291 INFO    HandlerThread:1507375 [system_monitor.py:probe():211] Finished collecting system info
2023-11-29 13:23:28,291 INFO    HandlerThread:1507375 [system_monitor.py:probe():214] Publishing system info
2023-11-29 13:23:28,291 DEBUG   HandlerThread:1507375 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-11-29 13:23:28,294 DEBUG   HandlerThread:1507375 [system_info.py:_save_pip():68] Saving pip packages done
2023-11-29 13:23:28,297 INFO    HandlerThread:1507375 [system_monitor.py:probe():216] Finished publishing system info
2023-11-29 13:23:28,324 DEBUG   SenderThread:1507375 [sender.py:send():380] send: files
2023-11-29 13:23:28,324 INFO    SenderThread:1507375 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-11-29 13:23:28,342 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: stop_status
2023-11-29 13:23:28,343 DEBUG   SenderThread:1507375 [sender.py:send():380] send: telemetry
2023-11-29 13:23:28,343 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-29 13:23:28,345 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: stop_status
2023-11-29 13:23:28,816 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-metadata.json
2023-11-29 13:23:28,817 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/requirements.txt
2023-11-29 13:23:29,179 INFO    wandb-upload_0:1507375 [upload_job.py:push():131] Uploaded file /tmp/tmphvnfjjerwandb/7jp0mntb-wandb-metadata.json
2023-11-29 13:23:31,855 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:23:36,856 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:23:37,823 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:23:39,826 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:23:42,823 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:23:43,340 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-29 13:23:43,340 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: stop_status
2023-11-29 13:23:43,342 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: stop_status
2023-11-29 13:23:47,836 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:23:48,489 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:23:53,844 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:23:54,193 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:23:58,358 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: stop_status
2023-11-29 13:23:58,359 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: stop_status
2023-11-29 13:23:58,366 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-29 13:23:59,586 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:24:00,854 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/config.yaml
2023-11-29 13:24:01,670 DEBUG   SenderThread:1507375 [sender.py:send():380] send: exit
2023-11-29 13:24:01,671 INFO    SenderThread:1507375 [sender.py:send_exit():585] handling exit code: 255
2023-11-29 13:24:01,671 INFO    SenderThread:1507375 [sender.py:send_exit():587] handling runtime: 33
2023-11-29 13:24:01,674 INFO    SenderThread:1507375 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-29 13:24:01,675 INFO    SenderThread:1507375 [sender.py:send_exit():593] send defer
2023-11-29 13:24:01,675 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:01,675 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 0
2023-11-29 13:24:01,676 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:01,676 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 0
2023-11-29 13:24:01,676 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 1
2023-11-29 13:24:01,676 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:01,676 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 1
2023-11-29 13:24:01,677 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:01,677 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 1
2023-11-29 13:24:01,677 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 2
2023-11-29 13:24:01,677 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:01,677 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 2
2023-11-29 13:24:01,678 INFO    HandlerThread:1507375 [system_monitor.py:finish():190] Stopping system monitor
2023-11-29 13:24:01,678 DEBUG   SystemMonitor:1507375 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-11-29 13:24:01,679 DEBUG   SystemMonitor:1507375 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-11-29 13:24:01,679 DEBUG   SystemMonitor:1507375 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-11-29 13:24:01,679 INFO    HandlerThread:1507375 [interfaces.py:finish():202] Joined cpu monitor
2023-11-29 13:24:01,684 INFO    HandlerThread:1507375 [interfaces.py:finish():202] Joined disk monitor
2023-11-29 13:24:01,856 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-summary.json
2023-11-29 13:24:02,981 INFO    HandlerThread:1507375 [interfaces.py:finish():202] Joined gpu monitor
2023-11-29 13:24:02,983 INFO    HandlerThread:1507375 [interfaces.py:finish():202] Joined memory monitor
2023-11-29 13:24:02,983 INFO    HandlerThread:1507375 [interfaces.py:finish():202] Joined network monitor
2023-11-29 13:24:02,984 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: poll_exit
2023-11-29 13:24:02,987 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:02,987 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 2
2023-11-29 13:24:02,987 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 3
2023-11-29 13:24:02,988 DEBUG   SenderThread:1507375 [sender.py:send():380] send: stats
2023-11-29 13:24:02,991 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: poll_exit
2023-11-29 13:24:02,988 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:02,992 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 3
2023-11-29 13:24:02,993 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:02,993 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 3
2023-11-29 13:24:02,994 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 4
2023-11-29 13:24:02,994 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:02,994 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 4
2023-11-29 13:24:02,995 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:02,995 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 4
2023-11-29 13:24:02,996 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 5
2023-11-29 13:24:02,996 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:02,996 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 5
2023-11-29 13:24:02,997 DEBUG   SenderThread:1507375 [sender.py:send():380] send: summary
2023-11-29 13:24:03,000 INFO    SenderThread:1507375 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-29 13:24:03,001 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:03,001 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 5
2023-11-29 13:24:03,001 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 6
2023-11-29 13:24:03,002 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:03,002 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 6
2023-11-29 13:24:03,003 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:03,003 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 6
2023-11-29 13:24:03,003 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 7
2023-11-29 13:24:03,004 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: status_report
2023-11-29 13:24:03,004 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:03,004 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 7
2023-11-29 13:24:03,005 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:03,005 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 7
2023-11-29 13:24:03,671 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: poll_exit
2023-11-29 13:24:03,861 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-summary.json
2023-11-29 13:24:03,862 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:24:05,655 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 8
2023-11-29 13:24:05,655 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: poll_exit
2023-11-29 13:24:05,655 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:05,656 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 8
2023-11-29 13:24:05,657 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:05,657 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 8
2023-11-29 13:24:05,657 INFO    SenderThread:1507375 [job_builder.py:build():281] Attempting to build job artifact
2023-11-29 13:24:05,658 INFO    SenderThread:1507375 [job_builder.py:_get_source_type():393] is repo sourced job
2023-11-29 13:24:05,667 INFO    SenderThread:1507375 [job_builder.py:build():369] adding wandb-job metadata file
2023-11-29 13:24:05,682 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 9
2023-11-29 13:24:05,683 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:05,683 DEBUG   SenderThread:1507375 [sender.py:send():380] send: artifact
2023-11-29 13:24:05,683 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 9
2023-11-29 13:24:05,863 INFO    Thread-12 :1507375 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
2023-11-29 13:24:08,548 INFO    wandb-upload_0:1507375 [upload_job.py:push():89] Uploaded file /home/yishido/.local/share/wandb/artifacts/staging/tmp5tvuxj3e
2023-11-29 13:24:08,580 INFO    wandb-upload_1:1507375 [upload_job.py:push():89] Uploaded file /home/yishido/.local/share/wandb/artifacts/staging/tmpuaf7d29s
2023-11-29 13:24:08,675 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: keepalive
2023-11-29 13:24:08,848 ERROR   Thread-11 (_thread_body):1507375 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-11-29 13:24:08,848 ERROR   Thread-11 (_thread_body):1507375 [internal_api.py:execute():370] {"errors":[{"message":"failed to find run self-supervised/9w8csl2q","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2023-11-29 13:24:08,852 ERROR   SenderThread:1507375 [sender.py:send_artifact():1458] send_artifact: failed for artifact "job/job-git_github.com_yuzuki-lab_self-supervised.git_stl_resnet.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-29 13:24:08,853 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:08,853 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 9
2023-11-29 13:24:08,854 INFO    SenderThread:1507375 [dir_watcher.py:finish():358] shutting down directory watcher
2023-11-29 13:24:08,866 INFO    SenderThread:1507375 [dir_watcher.py:finish():388] scan: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files
2023-11-29 13:24:08,867 INFO    SenderThread:1507375 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/config.yaml config.yaml
2023-11-29 13:24:08,867 INFO    SenderThread:1507375 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/requirements.txt requirements.txt
2023-11-29 13:24:08,875 INFO    SenderThread:1507375 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-metadata.json wandb-metadata.json
2023-11-29 13:24:08,876 INFO    SenderThread:1507375 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log output.log
2023-11-29 13:24:08,885 INFO    SenderThread:1507375 [dir_watcher.py:finish():402] scan save: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-summary.json wandb-summary.json
2023-11-29 13:24:08,891 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 10
2023-11-29 13:24:08,892 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:08,893 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 10
2023-11-29 13:24:08,894 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:08,894 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 10
2023-11-29 13:24:08,900 INFO    SenderThread:1507375 [file_pusher.py:finish():175] shutting down file pusher
2023-11-29 13:24:09,066 ERROR   wandb-upload_0:1507375 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-11-29 13:24:09,066 ERROR   wandb-upload_0:1507375 [internal_api.py:execute():370] {"errors":[{"message":"run self-supervised/9w8csl2q not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-29 13:24:09,067 ERROR   Thread-11 (_thread_body):1507375 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/config.yaml
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-29 13:24:09,081 ERROR   wandb-upload_1:1507375 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-11-29 13:24:09,186 ERROR   wandb-upload_1:1507375 [internal_api.py:execute():370] {"errors":[{"message":"run self-supervised/9w8csl2q not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-29 13:24:09,187 ERROR   Thread-11 (_thread_body):1507375 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/requirements.txt
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-29 13:24:09,410 ERROR   wandb-upload_2:1507375 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-11-29 13:24:09,410 ERROR   wandb-upload_2:1507375 [internal_api.py:execute():370] {"errors":[{"message":"run self-supervised/9w8csl2q not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-29 13:24:09,411 ERROR   Thread-11 (_thread_body):1507375 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/output.log
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-29 13:24:09,413 ERROR   wandb-upload_3:1507375 [internal_api.py:execute():369] 404 response executing GraphQL.
2023-11-29 13:24:09,414 ERROR   wandb-upload_3:1507375 [internal_api.py:execute():370] {"errors":[{"message":"run self-supervised/9w8csl2q not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-29 13:24:09,415 ERROR   Thread-11 (_thread_body):1507375 [step_upload.py:_handle_event():200] Failed to upload file: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2175, in upload_urls
    query_result = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-29 13:24:09,616 INFO    Thread-11 (_thread_body):1507375 [sender.py:transition_state():613] send defer: 11
2023-11-29 13:24:09,617 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:09,618 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 11
2023-11-29 13:24:09,619 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:09,620 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 11
2023-11-29 13:24:09,620 INFO    SenderThread:1507375 [file_pusher.py:join():181] waiting for file pusher
2023-11-29 13:24:09,620 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 12
2023-11-29 13:24:09,620 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:09,620 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 12
2023-11-29 13:24:09,621 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:09,621 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 12
2023-11-29 13:24:09,621 INFO    SenderThread:1507375 [file_stream.py:finish():595] file stream finish called
2023-11-29 13:24:09,797 INFO    SenderThread:1507375 [file_stream.py:finish():599] file stream finish is done
2023-11-29 13:24:09,797 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 13
2023-11-29 13:24:09,798 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:09,798 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 13
2023-11-29 13:24:09,799 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:09,799 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 13
2023-11-29 13:24:09,799 INFO    SenderThread:1507375 [sender.py:transition_state():613] send defer: 14
2023-11-29 13:24:09,799 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: defer
2023-11-29 13:24:09,800 INFO    HandlerThread:1507375 [handler.py:handle_request_defer():170] handle defer: 14
2023-11-29 13:24:09,800 DEBUG   SenderThread:1507375 [sender.py:send():380] send: final
2023-11-29 13:24:09,801 DEBUG   SenderThread:1507375 [sender.py:send():380] send: footer
2023-11-29 13:24:09,801 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: defer
2023-11-29 13:24:09,801 INFO    SenderThread:1507375 [sender.py:send_request_defer():609] handle sender defer: 14
2023-11-29 13:24:09,802 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: poll_exit
2023-11-29 13:24:09,803 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: poll_exit
2023-11-29 13:24:09,803 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: server_info
2023-11-29 13:24:09,804 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: get_summary
2023-11-29 13:24:09,805 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: sampled_history
2023-11-29 13:24:09,805 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: server_info
2023-11-29 13:24:09,805 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-29 13:24:09,810 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: job_info
2023-11-29 13:24:10,011 DEBUG   SenderThread:1507375 [sender.py:send_request():407] send_request: job_info
2023-11-29 13:24:10,012 INFO    MainThread:1507375 [wandb_run.py:_footer_history_summary_info():3554] rendering history
2023-11-29 13:24:10,012 INFO    MainThread:1507375 [wandb_run.py:_footer_history_summary_info():3586] rendering summary
2023-11-29 13:24:10,013 INFO    MainThread:1507375 [wandb_run.py:_footer_sync_info():3513] logging synced files
2023-11-29 13:24:10,013 DEBUG   HandlerThread:1507375 [handler.py:handle_request():144] handle_request: shutdown
2023-11-29 13:24:10,014 INFO    HandlerThread:1507375 [handler.py:finish():844] shutting down handler
2023-11-29 13:24:10,811 INFO    WriterThread:1507375 [datastore.py:close():294] close: /home/yishido/self_supervied/wandb/run-20231129_132326-9w8csl2q/run-9w8csl2q.wandb
2023-11-29 13:24:11,012 INFO    SenderThread:1507375 [sender.py:finish():1534] shutting down sender
2023-11-29 13:24:11,012 INFO    SenderThread:1507375 [file_pusher.py:finish():175] shutting down file pusher
2023-11-29 13:24:11,012 INFO    SenderThread:1507375 [file_pusher.py:join():181] waiting for file pusher
